#!/bin/bash

do_gosu(){
    user="$1"
    shift 1

    is_exec="false"
    if [ "$1" = "exec" ]; then
        is_exec="true"
        shift 1
    fi

    if [ "$(id -u)" = "0" ]; then
        if [ "${is_exec}" = "true" ]; then
            exec gosu "${user}" "$@"
        else
            gosu "${user}" "$@"
            return "$?"
        fi
    else
        if [ "${is_exec}" = "true" ]; then
            exec "$@"
        else
            eval '"$@"'
            return "$?"
        fi
    fi
}


if [[ "start" == "$1" ]]; then
    echo "Starting server"
    do_gosu "${PROJECT_USER}:${PROJECT_GROUP}" exec -c gunicorn \
      --name="${APPLICATION_NAME}" \
      --chdir="${PROJECT_PATH}"  \
      --worker-class eventlet -w 1 --log-level debug --timeout 300 --keep-alive 5 --access-logfile - app:app --bind 0.0.0.0:"${APP_PORT}"
fi

exec "$@"